### ISSUE TITLE
what‘s wrong with this:Exception in thread "main" when i run"./llfi-gui"

### ISSUE THREAD

**Issue by lidanfeng** [DependableSystemsLab/LLFI#83] opened 2016-03-24 03:49 UTC
gandalf@SZX1000074727:/mnt/llfi20160324/llfi/bin$ ./llfi-gui
/usr/local/jdk1.8.0_45/bin/java -classpath /usr/local/jdk1.8.0_45/./jre/lib/*:/usr/local/jdk1.8.0_45/./jre/lib/ext/*:/mnt/llfi20160324/llfisrc/./gui/application/lib/*:/mnt/llfi20160324/llfi/bin/../gui/application/lib/*:/mnt/llfi20160324/llfi/bin/../gui application.Main
gandalf@SZX1000074727:/mnt/llfi20160324/llfi/bin$ Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:68)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:263)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        ... 5 more

**Comment by karthikp-ubc** [comment] 2016-03-24 11:24
It's hard to determine what's wrong without knowing more about your setup. Can you please provide more details ? Also, are you able to run LLFI from the command line (say by running the tests) ?

**Comment by lidanfeng** [comment] 2016-03-25 03:50
most of the Pre-requisites i install automatic in my ubuntu,except YAML\LLVM,for some internet connect reasons;
I also have to download the packet manual which need by the script"InstallLLFI.py",and put them to the directory"downloads/"; then i run"python3 InstallLLFI.py".there isn't fatal error,so i follow the guide to run"./llfi-gui",but it cann't works

**Comment by karthikp-ubc** [comment] 2016-03-25 11:12
Did you run the tests ? See below for how to do this. If so, did all the tests pass successfully ? Thanks,

https://github.com/DependableSystemsLab/LLFI/wiki/Test-Suite-for-Regression-Test

**Comment by karthikp-ubc** [comment] 2016-03-30 14:00
Closing this issue as this is not the appropriate forum to post installation issues - please use the mailing list for the same

**Closed by karthikp-ubc** 2016-03-30 14:00 UTC

**Comment by Andre4102** [comment] 2020-10-26 18:09
I encountered a similar problem with my installation, how did you solved it?

**Comment by karthikp-ubc** [comment] 2020-10-26 22:30
Did the command line setup work for you and did the tests pass ? If not, please try that first. Also, the web-based GUI may be better as it has fewer system dependencies. It's functionally identical to the Java-based GUI for the most part. Let us know if this works.

**Comment by Andre4102** [comment] 2020-10-27 07:41
I installed llfi using the python script, because it was the recommanded way and it worked correctly. I'm currently running all the tests because this time they are working (last time I cheked I wasn't able to run them). [The first one here](https://github.com/DependableSystemsLab/LLFI/wiki/Test-Suite-for-Regression-Test) passed, when the complete test finishes I'll try using the web GUI. Thanks for the help and I'll update you later.

**Comment by Andre4102** [comment] 2020-10-27 15:19
I used the python script as recommended in the guide and all the tests pass. I tried using the web GUI but i canìt launch it. When i run webpack (with our without -w) it tells me i have to install webpack-cli, even if i'm using webpack <4.X.X. If i install a higher version of webpack and webpack-cli it still asks me to install webpack-cli and doesn't let me launch the web-GUI.

**Comment by karthikp-ubc** [comment] 2020-10-27 16:35
Thanks for letting us know. Support for the web GUI is experimental at 
this point and we'll look into the issue. We're unable to provide an ETA 
though.

- Karthik

**Comment by Andre4102** [comment] 2020-10-27 17:11
Do you have any idea on why the standard gui doesn't work properly? My guess is something related to Java, but I tried changing java version and I still got this error. Months ago I managed to use it properly, but then I had to re-install Ubuntu and I couldn't make it work since then. I'm using Ubuntu 20.04 right now.
