### ISSUE TITLE
input.yaml:ERROR:Unknown Instruction selection method in input.yaml 

### ISSUE THREAD

**Issue by zuiaiziai** [DependableSystemsLab/LLFI#119] opened 2018-09-30 07:32 UTC
hello,
When I use factorial file in the test_programs directory to test LLFI with the command '<LLFI_BUILD_ROOT>/bin/instrument --readable factorial.ll', I get an error: Unknown Instruction selection method in input.yaml. I try many times,but I can't resolve this problem.
The contents below is the input.yaml file in factorial file:
compileOption:
    instSelMethod:
      - insttype:
          include: 
            - all
          exclude:
            - ret

    regSelMethod: regloc
    regloc: dstreg

runOption:
    - run:
        numOfRuns: 1
        fi_type: bitflip
I use Ubuntu 14.04 LTS and test LLFI based on LLVM-2.9. What do you mean about 'something wrong with your setup'? Would you have any idea about the problem I encountered? Thank you very much!
Could you help me to find the problem? Thank you very much! Please answer here or email me at 1090366769@qq.com.

**Comment by karthikp-ubc** [comment] 2018-09-30 18:06
We will look into it and get back to you- thanks for your patience.

**Comment by zuiaiziai** [comment] 2018-10-02 02:49
Ok, thank you very much! I will be patient.

**Comment by karthikp-ubc** [comment] 2018-11-04 01:37
I believe this issue has been resolved based on offline communications between you and lpalazzi, so I'm closing this - please feel free to reopen it if it's still unresolved (I also closed a duplicate of this issue).

**Closed by karthikp-ubc** 2018-11-04 01:37 UTC
