### ISSUE TITLE
when i execute the step3,it has error as this.

### ISSUE THREAD

**Issue by lidanfeng** [DependableSystemsLab/LLFI#85] opened 2016-03-28 07:27 UTC
root@SZX1000074727:/mnt/llfi20160324/llfi/test_suite/HardwareFaults/insttype# cat llfi.test.log.instrument.txt 
_**Error opening '/mnt/llfi20160324/llfi/bin/../llvm_passes/llfi-passes.so': /mnt/llfi20160324/llfi/bin/../llvm_passes/llfi-passes.so:**_ undefined symbol: _ZN4llvm2cl3optISsLb0ENS0_6parserISsEEE15setInitialValueERKSs
-load request ignored.
opt: Unknown command line argument '-genllfiindexpass'. Try: '/mnt/llfi20160324/llvm/bin/opt -help'
opt: Did you mean '-inline-cost'?

ERROR: there was an error during running the instrumentation pass, please follow the provided instructions for instrument.

**Comment by karthikp-ubc** [comment] 2016-03-30 13:59
Closing this issue as it's not possible to determine root cause from just one message. Also, this is not the appropriate forum to post installation issues - please use the mailing list for the same.

**Closed by karthikp-ubc** 2016-03-30 13:59 UTC
