### ISSUE TITLE
about fi_cycle in injectfault script in bin

### ISSUE THREAD

**Issue by timberjack** [DependableSystemsLab/LLFI#66] opened 2015-06-17 01:54 UTC
Dear author,

I am trying to study into the scripts of LLFI recently.

About the problem, I feel it is a little bit odd about fi_cycle. I think this variable is defined to be a param to stand for in which cycle the fault should be injected to (I am not sure this understanding), but I find that in "injectfault.py" script, fi_cycle is just read from input.yaml or generated randomly, without influencing the execution of faultinjection.exe. Does it mean that fi_cycle does actually no effect?

Thanks,
Xianan

**Comment by karthikp-ubc** [comment] 2015-06-18 16:33
Your understanding of what fi_cycle is doing is correct. Basically, it tells you in which invocation of the fault injection site the fault should be injected. So perhaps the word cycle is a misnomer - it should be execution count. That said, the parameter should influence faultinjection.exe. We'll look into this issue.

@karfair can you please take a look at this and see if we're able to reproduce this issue ? Thanks,

- Karthik

**Comment by karfair** [comment] 2015-06-19 05:44
From what I understand, the injectfault.py script either generates a random fi_cycle or reads a fi_cycle from the input.yaml and writes it into llfi.config.runtime.txt. The fault injection executable then automatically reads the injection settings from this file.

**Comment by karthikp-ubc** [comment] 2015-06-20 03:27
It looks like this is a non-issue as the fault injection executable does take the fi_cycle into account, so I'm closing it. Please reopen it if there is still an issue. Thanks.

- Karthik

**Closed by karthikp-ubc** 2015-06-20 03:27 UTC
